### PR TITLE
Fixed: Undefined array key "QUERY_STRING"

### PR DESCRIPTION
**Pull request by Ahmard**
The above warning is thrown when page is accessed without pagination query param.
I am using PHP 8.0 by the way.

### CODE REVIEW

**Comment by stefangabos** [comment]
This is now fixed, please download latest commit (a release will also come)
https://github.com/stefangabos/Zebra_Pagination/archive/refs/heads/master.zip

**Comment by Ahmard** [comment]
Okay, thanks.

**Comment by Ahmard** [comment]
A release will be better, cause I install the library using composer.

**Comment by stefangabos** [comment]
release is coming soon. i am pushing some new updates today. if you'd be so kind to use the library for a day or two and see if it breaks, i'd be making a new release as soon as you confirm that it is working

**Comment by Ahmard** [comment]
Okay, I will try using it.

**Pull request closed without merging**
